name: Google Cloud Run Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  deploy:

    name: Google Cloud Run Deploy
    runs-on: ubuntu-latest
    env:
      GCR_IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }}
      DOCKER_HUB_IMAGE_NAME: kineticsquid/${{ secrets.GCP_APPLICATION }}
    steps:

      - name: Google Cloud Login
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Gcloud Docker
        run: gcloud auth configure-docker --quiet

      - name: Checkout repository
        uses: actions/checkout@v2

#      - name: Build gcr.io Docker image
#        run: docker build . -t $GCR_IMAGE_NAME
#
#      - name: Push gcr.io Docker image
#        run: docker push $GCR_IMAGE_NAME

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build hub.docker.com Docker image
        run: docker build . -t $DOCKER_HUB_IMAGE_NAME

      - name: Push hub.docker.com Docker image
        run: docker push $DOCKER_HUB_IMAGE_NAME

      - name: Google Cloud Deploy
        run: gcloud run deploy ${{ secrets.GCP_APPLICATION }} --allow-unauthenticated --project cloud-run-stuff --region us-central1 --source ./

      - name: Google Cloud Image Deploy
        run: gcloud run deploy ${{ secrets.GCP_APPLICATION }}2 --image $DOCKER_HUB_IMAGE_NAME --allow-unauthenticated --project cloud-run-stuff --region us-central1 --platform managed


